version: "3.9"

networks:
  jenkins:
    name: jenkins
    driver: bridge

volumes:
  jenkins_home:

services:
  jenkins:
    build:
      context: ./jenkins/
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.azure:/root/.azure
    networks:
      - jenkins
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ~/ssl:/etc/nginx/ssl
    depends_on:
      - jenkins
    networks:
      - jenkins
